# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________
- The four main datatypes in SQLite 3 are TEXT, INTEGER, REAL, and BLOB. Other common datatypes are usable as SQLite3 is able to place the datatype into one of its 4 main datatypes.




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
- Primary keys are unique identifiers for a table and are considered unqiue values for a column entry, while foreign keys are primary keys from another table, allowing for tables to be joined.




## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
- One-to-One relationships occur when a single record in the first table is related to a single record in the second table and vice versa.
- One-to-Many relationships occur when a single record in the first table is related to multiple records in the second table, while a single record in the second table is related to a single record in the first table.
- Many-to-Many relationships occur when a single record in the first table is related to multiple records in the second table and a single record in the second table is related to multiple records in the first table.

## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
- Inner joins select records from the first table and second table that have matching values.
- Left joins select all records from the first table and the matching values from the second table.
- Right joins select all records from the second table and the matching values from the first table.
- Full joins select all records from the first table and second table when there is a match in either the first or second table.


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
- Aggregate functions allow the user to apply certain functions within the SELECT query, while the GROUP BY statement is used to group the data together that the aggregate function is being applied to.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________
- Associative entities are the tables constructed to associate two other tables in a many-to-many JOIN.


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.